services:
  tomcat:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_RSA_KEY=${SNOWFLAKE_RSA_KEY}
      - SNOWFLAKE_RSA_KEY_PASSWORD=${SNOWFLAKE_RSA_KEY_PASSWORD}
      - SNOWFLAKE_HOSTNAME=${SNOWFLAKE_HOSTNAME}
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
